global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "envoy"

    # Override global settings
    scrape_interval: 30s
    metrics_path: /stats/prometheus
    static_configs:
      - targets: ["envoy:9901"]
